package model;
// Generated Jan 23, 2017 3:49:03 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name="AUTHORITY"
    ,schema="dbo"
    ,catalog="SOAPORTAL"
)
public class Authority  implements java.io.Serializable {


     private AuthorityId id;
     private String creator;
     private Date createTime;
     private String modifier;
     private Date modifyTime;

    public Authority() {
    }

	
    public Authority(AuthorityId id, String creator, Date createTime) {
        this.id = id;
        this.creator = creator;
        this.createTime = createTime;
    }
    public Authority(AuthorityId id, String creator, Date createTime, String modifier, Date modifyTime) {
       this.id = id;
       this.creator = creator;
       this.createTime = createTime;
       this.modifier = modifier;
       this.modifyTime = modifyTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="roleId", column=@Column(name="ROLE_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="catalogId", column=@Column(name="CATALOG_ID", nullable=false, length=30) ) } )
    public AuthorityId getId() {
        return this.id;
    }
    
    public void setId(AuthorityId id) {
        this.id = id;
    }

    
    @Column(name="CREATOR", nullable=false, length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", nullable=false, length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="MODIFIER", length=20)
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_TIME", length=23)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


