package model;
// Generated Oct 19, 2017 5:20:20 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DevTestId generated by hbm2java
 */
@Embeddable
public class DevTestId  implements java.io.Serializable {


     private Long col1;
     private Long col2;
     private Long col3;

    public DevTestId() {
    }

    public DevTestId(Long col1, Long col2, Long col3) {
       this.col1 = col1;
       this.col2 = col2;
       this.col3 = col3;
    }
   


    @Column(name="col1")
    public Long getCol1() {
        return this.col1;
    }
    
    public void setCol1(Long col1) {
        this.col1 = col1;
    }


    @Column(name="col2")
    public Long getCol2() {
        return this.col2;
    }
    
    public void setCol2(Long col2) {
        this.col2 = col2;
    }


    @Column(name="col3")
    public Long getCol3() {
        return this.col3;
    }
    
    public void setCol3(Long col3) {
        this.col3 = col3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DevTestId) ) return false;
		 DevTestId castOther = ( DevTestId ) other; 
         
		 return ( (this.getCol1()==castOther.getCol1()) || ( this.getCol1()!=null && castOther.getCol1()!=null && this.getCol1().equals(castOther.getCol1()) ) )
 && ( (this.getCol2()==castOther.getCol2()) || ( this.getCol2()!=null && castOther.getCol2()!=null && this.getCol2().equals(castOther.getCol2()) ) )
 && ( (this.getCol3()==castOther.getCol3()) || ( this.getCol3()!=null && castOther.getCol3()!=null && this.getCol3().equals(castOther.getCol3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCol1() == null ? 0 : this.getCol1().hashCode() );
         result = 37 * result + ( getCol2() == null ? 0 : this.getCol2().hashCode() );
         result = 37 * result + ( getCol3() == null ? 0 : this.getCol3().hashCode() );
         return result;
   }   


}


