package model;
// Generated Oct 19, 2017 5:20:20 PM by Hibernate Tools 4.0.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DevTest generated by hbm2java
 */
@Entity
@Table(name="dev_test"
    ,schema="public"
)
public class DevTest  implements java.io.Serializable {


     private DevTestId id;

    public DevTest() {
    }

    public DevTest(DevTestId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="col1", column=@Column(name="col1") ), 
        @AttributeOverride(name="col2", column=@Column(name="col2") ), 
        @AttributeOverride(name="col3", column=@Column(name="col3") ) } )
    public DevTestId getId() {
        return this.id;
    }
    
    public void setId(DevTestId id) {
        this.id = id;
    }




}


